platform: linux

image_resource:
  type: docker-image

inputs:
  - name: bin_gpdb
  - name: pljava_src
  - name: m2repository

outputs:
  - name: pljava_gppkg

run:
  path: pljava_src/concourse/scripts/build_pljava.sh
params:
  OSVER:
  PL_GP_VERSION:
